app/lib/kokuraex_web/router.ex
defmodule KokuraexWeb.Router do
  use KokuraexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {KokuraexWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", KokuraexWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/about", AboutController, :index
    get "/event", EventController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", KokuraexWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: KokuraexWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

app/lib/kokuraex/application.ex
defmodule Kokuraex.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Telemetry supervisor
      KokuraexWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Kokuraex.PubSub},
      # Start the Endpoint (http/https)
      KokuraexWeb.Endpoint
      # Start a worker by calling: Kokuraex.Worker.start_link(arg)
      # {Kokuraex.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Kokuraex.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    KokuraexWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

app/lib/kokuraex/mailer.ex
defmodule Kokuraex.Mailer do
  use Swoosh.Mailer, otp_app: :kokuraex
end

app/lib/kokuraex_web/controllers/about_controller.ex
defmodule KokuraexWeb.AboutController do
  use KokuraexWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

app/lib/kokuraex_web/controllers/event_controller.ex
defmodule KokuraexWeb.EventController do
  use KokuraexWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

app/lib/kokuraex_web/controllers/page_controller.ex
defmodule KokuraexWeb.PageController do
  use KokuraexWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

app/lib/kokuraex_web/views/about_view.ex
defmodule KokuraexWeb.AboutView do
  use KokuraexWeb, :view
end

app/lib/kokuraex_web/views/error_view.ex
defmodule KokuraexWeb.ErrorView do
  use KokuraexWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

app/lib/kokuraex_web/views/event_view.ex
defmodule KokuraexWeb.EventView do
  use KokuraexWeb, :view
end

app/lib/kokuraex_web/views/layout_view.ex
defmodule KokuraexWeb.LayoutView do
  use KokuraexWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

app/lib/kokuraex_web/views/page_view.ex
defmodule KokuraexWeb.PageView do
  use KokuraexWeb, :view
end

app/lib/kokuraex_web/templates/about/index.html.heex
<div class="flex flex-col max-w-3xl mx-auto">
  <h1 class="text-center text-4xl font-bold text-purple-600">
    About
  </h1>
  <div class="flex flex-col text-center mt-8">
    <img
      src={Routes.static_path(@conn, "/images/img_kokuraex_icon.png")}
      alt="kokura.ex logo"
      class="w-52 mx-auto"
    >
    <p class="mt-8 text-left font-midium">
      <strong>kokura.ex</strong>は、「高速処理性能」と「高い開発効率性」を両立できるプログラミング言語<strong>Elixir</strong>と、そのWebアプリケーションフレームワーク<strong>Phoenix</strong>を北九州で広め、ワイワイと盛り上げていくコミュニティです。<br>
      これから北九州で先端技術をやりたい方や、最新のプログラミングを学びたい方、未来に向けてITに強くなりたい方など、技術への興味レベルが高い方や、プログラミングに関心が高い方のご参加を歓迎します。
    </p>
    <small class="mt-5 text-left">
      kokura.ex is a community that promotes the Elixir programming language and its web application framework, Phoenix, in Kitakyushu, where both "high-speed processing performance" and "high development efficiency" can be achieved.<br>
      We welcome people with a high level of interest in technology and programming, such as those who want to work with cutting-edge technology in Kitakyushu, those who want to learn the latest programming, and those who want to be strong in IT for the future.
    </small>
  </div>

  <div class="flex flex-col text-center mt-16">
    <h1 class="text-center text-4xl font-medium text-gray-600">
      Elixir / Phoenix
    </h1>
    <div class="flex mt-12 mx-auto">
      <img
        src={Routes.static_path(@conn, "/images/img_elixir.png")}
        alt="kokura.ex Logo"
        class="w-auto h-32"
      >
      <img
        src={Routes.static_path(@conn, "/images/img_phoenix.png")}
        alt="kokura.ex Logo"
        class="w-auto h-32"
      >
    </div>
    <div class="mt-12 text-left font-midium">
      <p>
        近年のElixir／Phoenixは、
        <ul>
          <li>　マルチコアのCPU全てをフル活用できる「Flow」や「GenStage」、</li>
          <li>　動的生成されたマルチプロセスを監視・自動再起動できる「Dynamic Supervisor」、</li>
          <li>　Webフレームワーク「Phoenix」のHTTP/2対応やwebpack対応、</li>
          <li>　IoTコアライブラリ「Nerves」と、クラウド上からファームウェア更新を叶える</li>「NervesHub」
        </ul>
        といったElixirならではの革新的な独自機能を出しつつ、「Elixir／Phoenixのみで、Webプロダクト開発やSI案件開発を不自由無く行える」フェーズへと進化しています。
      </p>
      <p class="mt-5">
        2014～2015年付近は、Elixirも未だ未成熟で、「Erlangを覚えなければElixirは使えない」という認識が一般的でしたが、現状は、Elixir単独で充分にプロダクト開発／SI案件開発を行える状況へと変わってきています。<br>
        また、2017年にはGCP（Google Cloud Platform）でのElixir採用、2018年にはAWSでのカスタムランタイム採用、といった、大手クラウドでのElixir採用という追い風もありました。
      </p>
      <p class="mt-5">
        福岡においても、Elixir／Phoenixをプロダクト開発／SI案件開発で採用されるケースが増え、他言語よりも明らかにレスポンス速度が速いWeb+DBが数日で構築できた事例や、1年以上ダウンせずに運用が回った事例など、実運用の実績も増えています（福岡以外でも、SlackやLINE、ニコニコ動画、mixi、gumi等での活用事例もあります）。<br>
        全世界で見れば、2014年は、200社程度しか採用していなかったのが、2016年は1,100社を超え、現在は、ゲームサーバだけに限らず、フィンランドやスウェーデン、イギリスを始めとする、金融／証券／SNS／メッセージング基盤などの分野で活用されており、世界的にも有名なSlackやDiscordでも積極的に活用されています。
      </p>
      <p class="mt-5">
        そしてElixir／Phoenixにとっての2019年は、以下を完備し、スマホ開発やクラウドへの接続性も大幅に増強されました。<br>
        <ul>
          <li>Phoenixで、JavaScript無のElixirのみで、フロント処理を動的生成できる「LiveView」</li>
          <li>対障害性を備え、Amazon SQSとも接続できる並列ライブラリ「Broadway」</li>
          <li>Prometheus等の外部監視系への容易な接続を実現する「Telemetry」</li>
        今は、まさにElixir／Phoenixを始めるには、もっとも美味しいタイミングと言えるでしょう。
        </ul>
      </p>
      <p class="mt-5">
        海外と福岡のおける導入企業／規模／事例は、
        <a
          href="https://fukuokaex.fun/about"
          class="font-semibold text-purple-800 hover:opacity-75"
        >
          fukuoka.exポータルサイト
        </a>
        にて紹介しています。<br>
        更に、kokura.ex／fukuoka.exでは、これまでの言語では表現できなかったような次世代の高生産性Web／API開発スタイルの確立や、大規模インフラでもDBサーバをネックにしないためのスケールアウトの仕組み、ElixirとGCP上のAIエンジンを繋いだ画像解析システム、数倍のパフォーマンスを発揮できるGPU／FPGA活用、Elixirプロセスよりも更に軽量なプロセスライブラリ実装、ElixirによるElixirコンパイラ開発といった、先端領域でのElixir活用も、今まさに熱く展開しています。
      </p>
    </div>
    <small class="mt-5 text-left">
      <p>
        In recent years, Elixir/Phoenix has developed a number of new features;<br>
        - Flow and GenStage, which allow full utilization of all multi-core CPUs<br>
        - Dynamic Supervisor, which monitors and automatically restarts dynamically generated multi-processes, and the ability to create new processes<br>
        - HTTP/2 support and webpack support for the Phoenix web framework<br>
        - IoT core library "Nerves" and "NervesHub" for firmware updates from the cloud.<br>
        Elixir is evolving into a phase where web product development and SI project development can be done without any problems using only Elixir/Phoenix.
      </p>
      <p class="mt-2">
        Around 2014-2015, Elixir was still in its infancy, and the general perception was that "if you don't learn Erlang, you can't use Elixir", but the current situation has changed to the point where Elixir alone is sufficient for product development and SI project development.<br>
        However, the current situation has changed to the point where Elixir is sufficient to develop products and SI projects on its own. In addition, there has been a tailwind from the adoption of Elixir by major clouds, such as the adoption of Elixir by GCP (Google Cloud Platform) in 2017 and the adoption of custom runtimes by AWS in 2018.
      </p>
      <p class="mt-2">
        In Fukuoka, there are more and more cases of Elixir/Phoenix being used in product development and SI project development, and there are more and more actual operational results, such as a case where a Web+DB with clearly faster response speed than other languages could be built in a few days, and a case where operations ran for more than a year without downtime. (Outside of Fukuoka, there are also cases of use at Slack, LINE, Nico Nico Douga, mixi, gumi, etc.).<br>
        Currently, it is used not only in game servers, but also in the fields of finance, securities, SNS, and messaging infrastructure in countries such as Finland, Sweden, and the UK. It is also being actively used in the world famous Slack and Discord.
      </p>
      <p class="mt-2">
        And 2019 for Elixir/Phoenix has been greatly augmented with smartphone development and connectivity to the cloud, complete with the following;<br>
        - LiveView," which allows Phoenix to dynamically generate front-end processing using only Elixir, no JavaScript<br>
        - Broadway, a parallel library that is fault tolerant and can connect to Amazon SQS<br>
        - Telemetry, which enables easy connection to external monitoring systems such as Prometheus.<br>
        Now is the best time to start using Elixir/Phoenix.
      </p>
      <p class="mt-2">
        Companies, scale, and case studies in overseas and Fukuoka are introduced on the
        <a
          href="https://fukuokaex.fun/about"
          class="font-semibold text-purple-800 hover:opacity-75"
        >
          fukuoka.ex portal site.
        </a>
        <br>
        In addition, kokura.ex/fukuoka.ex has established a next generation high productivity web/API development style that could not be expressed in conventional languages, a scale-out mechanism to avoid bottlenecking the DB server even in a large scale infrastructure, an image analysis system that connects Elixir and an AI engine on GCP, a GPU/FPGA that can perform several times better than the Elixir process, and a system that can be used as a platform for the development of new applications. Elixir is also being used in cutting-edge areas such as image analysis systems that connect Elixir and AI engines on GCP, GPU/FPGA utilization that can deliver several times higher performance, process library implementations that are even lighter than Elixir processes, and Elixir compiler development using Elixir.
      </p>
    </small>
  </div>
</div>

app/lib/kokuraex_web/templates/event/index.html.heex
<div class="flex flex-col max-w-3xl mx-auto">
  <h1 class="text-center text-4xl font-bold text-purple-600">
    Event
  </h1>
</div>

app/lib/kokuraex_web/templates/layout/app.html.heex
<main>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

app/lib/kokuraex_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

app/lib/kokuraex_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Kokuraex", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="bg-gradient-to-t from-indigo-300 to-white">
    <div class="mx-5 mt-3 flex flex-col min-h-screen">
      <header>
        <section class="flex">
          <div class="w-4/12">
            <a href={Routes.page_path(@conn, :index)}>
              <img
                src={Routes.static_path(@conn, "/images/img_header.png")}
                alt="kokura.ex Logo"
                class="w-4/6"
              />
            </a>
          </div>
          <div class="w-6/12">
          </div>
          <div class="w-2/12 max-w-xs flex">
            <a
              href="https://twitter.com/search?q=%23kokuraex"
              class="w-1/2 hover:opacity-75"
            >
              <img
                src={Routes.static_path(@conn, "/images/img_twitter.jpg")}
                alt="twitter #kokuraex"
                class="rounded-3xl w-5/6"
              >
            </a>
            <a
              href="https://elixirjp.slack.com/archives/CPMB7CFPZ"
              class="w-1/2 hover:opacity-75"
            >
              <img
                src={Routes.static_path(@conn, "/images/img_slack.png")}
                alt="slack #kokura-ex"
                class="rounded-3xl w-5/6"
              >
            </a>
          </div>
        </section>
        <section>
          <ul class="flex mt-2 text-xl font-bold text-yellow-500 w-2/3 mx-auto sticky">
            <li class="flex-grow text-center hover:opacity-75">
              <%= link "Home", to: Routes.page_path(@conn, :index) %>
            </li>
            <li class="flex-grow text-center hover:opacity-75">
              <%= link "About", to: Routes.about_path(@conn, :index) %>
            </li>
            <li class="flex-grow text-center hover:opacity-75">
              <%= link "Event", to: Routes.event_path(@conn, :index) %>
            </li>
          </ul>
        </section>
      </header>

      <main class="flex-grow mt-8 text-gray-800">
        <%= @inner_content %>
      </main>

      <footer class="text-center mt-16 mb-3">
        <p>© 2021 kokura.ex</p>
      </footer>
    </div>
  </body>
</html>

app/lib/kokuraex_web/templates/page/index.html.heex
<div class="flex flex-col">
  <div class="flex flex-col text-center">
    <h1 class="text-lg font-bold text-purple-600">
      kokura.exは開発言語Elixirをわいわい盛り上げていく技術コミュニティです
    </h1>
    <p class="text-gray-500">
      kokura.ex is a technical community that promotes the Elixir language with fun and exciting
    </p>
  </div>

  <figure class="mt-3 mb-8 mx-auto">
    <img
      src={Routes.static_path(@conn, "/images/img_kokuraex.png")}
      alt="kokura.ex"
      class="rounded-md"
    >
  </figure>

  <div class="max-w-2xl mx-auto">
    <p class="font-midium mb-3">
      <strong>kokura.ex</strong>は、「高速処理性能」と「高い開発効率性」を両立できるプログラミング言語<strong>Elixir</strong>と、そのWebアプリケーションフレームワーク<strong>Phoenix</strong>を北九州で広め、ワイワイと盛り上げていくコミュニティです。
    </p>
    <p>
      kokura.ex is a community that promotes the Elixir programming language and its web application framework, Phoenix, in Kitakyushu, where both "high-speed processing performance" and "high development efficiency" can be achieved.
    </p>
  </div>
</div>